### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xxiane**
Just a small thing. I'm new to Hunspell and thought knowing that line would've been useful.

### CODE REVIEW

**Comment by thomas-joiner** [comment]
The installation of the hunspell library should not have an effect on the build, as the build uses the included binaries for each of the platforms that it can be used on (see the folders/files in `src/main/resources/lib/`).

As for the link to Maven Central, I would prefer just mentioning that the library is available on Maven Central, and providing the dependency boilerplate, e.g.

```xml
<dependency>
    <groupId>com.atlascopco</groupId>
    <artifactId>hunspell-bridj</artifactId>
    <version>1.0.4</version>
</dependency>
```

Due to the fact that maven central may in the future choose to change their site organization for the public-facing site.

Also, please leave the empty line between the build and project status as I prefer to keep the icons on separate lines.

**Comment by xxiane** [comment]
Oh, ok. I changed it back and put a Maven section at the bottom.

**Comment by thomas-joiner** [comment]
Thank you for the help.

**Comment by xxiane** [comment]
Thanks for putting up with such minor details!

**Pull request merged**
